from __future__ import annotations

CONTINUOUS_CUSTOM_ID_PREFIX = "pe:ca:"

CONT_DEFAULT_MIN_TOTAL_VOTES = 1
CONT_DEFAULT_APPROVAL_THRESHOLD_PERCENT = 51.0
CONT_DEFAULT_VOTING_DURATION_TEXT = "7天"
CONT_DEFAULT_COOLDOWN_DURATION_TEXT = "7天"

CONT_CONFIG_ACTIVE = "active"
CONT_CONFIG_ARCHIVED = "archived"

CONT_MODE_APPROVAL = "approval_vote"
CONT_MODE_SUPPORT = "support_collection"

CONT_MODE_LABELS = {
    CONT_MODE_APPROVAL: "同意/反对投票",
    CONT_MODE_SUPPORT: "支持票收集",
}

CONT_APP_VOTING = "voting"
CONT_APP_REVIEW_AREA_PENDING = "review_area_pending"
CONT_APP_REVIEWING = "reviewing"
CONT_APP_REVIEW_TIMEOUT = "review_timeout"
CONT_APP_REVIEW_PUBLISH_PENDING = "review_publish_pending"
CONT_APP_REVIEW_REJECTED = "review_rejected"
CONT_APP_APPROVED = "approved"
CONT_APP_REJECTED = "rejected"
CONT_APP_RETURNED = "returned"
CONT_APP_WITHDRAWN = "withdrawn"
CONT_APP_APPROVED_WITHDRAWN = "approved_withdrawn"
CONT_APP_CANCELLED = "cancelled"

CONT_FINAL_STATUSES = (
    CONT_APP_APPROVED,
    CONT_APP_REJECTED,
    CONT_APP_RETURNED,
    CONT_APP_WITHDRAWN,
    CONT_APP_APPROVED_WITHDRAWN,
    CONT_APP_CANCELLED,
)

CONT_VOTE_YES = "yes"
CONT_VOTE_NO = "no"
CONT_VOTE_SUPPORT = "support"

CONT_VOTE_CHOICES = (CONT_VOTE_YES, CONT_VOTE_NO, CONT_VOTE_SUPPORT)

CONT_APPLICATION_STATUS_LABELS = {
    CONT_APP_REVIEW_AREA_PENDING: "等待创建审核区",
    CONT_APP_REVIEWING: "前置审核中",
    CONT_APP_REVIEW_TIMEOUT: "审核超时",
    CONT_APP_REVIEW_PUBLISH_PENDING: "审核通过，等待发布",
    CONT_APP_REVIEW_REJECTED: "前置审核拒绝",
    CONT_APP_VOTING: "投票中",
    CONT_APP_APPROVED: "已通过",
    CONT_APP_REJECTED: "未通过",
    CONT_APP_RETURNED: "已打回修改",
    CONT_APP_WITHDRAWN: "已主动退出",
    CONT_APP_APPROVED_WITHDRAWN: "已退出通过名单",
    CONT_APP_CANCELLED: "已取消",
}

CONT_VOTE_LABELS = {
    CONT_VOTE_YES: "同意",
    CONT_VOTE_NO: "反对",
    CONT_VOTE_SUPPORT: "支持",
}

CONT_MAX_FIELDS = 25
